### ISSUE TITLE
provision for a female connector on the other side of the current edge connector ?

### ISSUE THREAD

**Issue by shodanx2** [platima/ESP32-CX-Riser#3]
To allow the ability to daisy chain them maybe ? 

Also, what about using the M.2 connector ? 
It is a high integrity connector with many pins and that gives you a good source for a good yet cheap connector

**Comment by platima** [comment]
1. No valid use case I can think of for this, and the ESP MCU's don't really have functionality that would support it.

2. M2 is for a very different purpose

**Comment by shodanx2** [comment]
I mean it's a commonly available, high quality and low cost 66 pins connector.

I'm not saying to make the esp32 an M.2 NVME device.

However, I also had a look at the spec and M.2 Key E config supports USB 2.0, I2C, SDIO, UART, PCM at 3.3v.

But really, my point is that it's a ready made, high pin count female edge connector so you can break out more of the esp32's peripherals and GPIO.

What is this riser meant to plug into ? I had a look at the hackster.io page and either it's not there or I can't find it.

Another approach is the castelate the edge pins so they can be soldered to a motherboard as shown below

![image](https://github.com/platima/ESP32-CX-Riser/assets/10621885/e5284216-527b-462a-81d0-d938e4c74aa2)

**Comment by platima** [comment]
You are right that it's definitely a good connector, and I apologise if I came across a short or sharp - I've just been getting a LOT of suggestions and am trying to filter them as best I can!

At this point it does not really align with this project or the use case. The most recent Youtube video (and probably the others) along wit the Hackster project explain more about what the goals are, but primarily being able to use it vertically or horizontally in much the same fashion that you'll find small ESP32's in IoT products. Eg in the Athom plug that I show at the start of the most recent video, or if you check out https://www.youtube.com/watch?v=UcyY1o26e4I you'll see how they are mounted and used in a lot of lights albeit those are extremely restricted.

An M.2 22x30mm variant could definitely be something for the future, and you're welcome to create that variant if you want. I just have no need for it, as the M.2 connector would not fit on my projects, and this project is purely for me, not to make a mass-produced product or make money 😅 Either way, I have created a new 'Suggestions' section in Notion and added M.2 to it (and the LiPo BMS idea), so I can track how many people want or suggest this.

On that point, I think the M.2 connection would be overkill for these MCUs. The ESP32-C3 that I am primarily basing it on has 15 GPIOs, which are almost all exposed - IO02 is not exposed and I honestly don't recall why but I am sure there was a reason haha. Maybe because it's a strapping pin? Could easily be added to V1.2 though. The C6 has 22 GPIOs so probably worth a slight rework in V1.2 to accommodate those extra GPIOs, and if I was going to make it slightly bigger like that (although I am VERY resistant to making it bigger than a stamp) then I could fit a LiPo connector, BMS, and .... a neat idea I just had inspired by your earlier deep sleep remark haha. Keeping it quiet for now to see if anyone else suggests it!

Castelating the pins like that is a brilliant idea though, and I have been really thinking about something similar as discussed in the videos. For the V1.1 revision I tried to work towards this, especially with 2.54mm pin spacing, but did not get there before I ran out of time. There are also components on both sides, so it would need to be soldered to the edge of another board, but my goal was mainly to allow header pins to be soldered on for offset horizontal mounting.

FYI if you want a M.2 ESP then https://www.sparkfun.com/products/16781 looks pretty neat too!

I'll open 'Discussions' for each of these ideas, and again, sorry for being a moody prick and thank you for your input!
